/*
 * Generated by Bluespec Compiler (build 102a30c)
 * 
 * On Mon Feb  1 21:37:17 PST 2021
 * 
 */
#include "bluesim_primitives.h"
#include "mkProcessor.h"


/* String declarations */
static std::string const __str_literal_6("Dumping the state of the processor", 34u);
static std::string const __str_literal_8("Quitting simulation.", 20u);
static std::string const __str_literal_4("Reached unsupported instruction", 31u);
static std::string const __str_literal_5("Total Clock Cycles = %d\nTotal Instruction Count = %d",
					 52u);
static std::string const __str_literal_9("[0x%8x:0x%04x] \t\t Mem read from 0x%08x\n", 39u);
static std::string const __str_literal_10("[0x%8x:0x%04x] \t\t Mem write 0x%08x to 0x%08x\n", 45u);
static std::string const __str_literal_3("[0x%8x:0x%04x] Executing\n", 25u);
static std::string const __str_literal_11("[0x%8x:0x%04x] Writeback writing %x to %d\n", 42u);
static std::string const __str_literal_2("[0x%8x:0x%04x] decoding 0x%08x\n", 31u);
static std::string const __str_literal_1("[0x%8x:0x%4x] Fetching instruction count 0x%4x\n", 47u);
static std::string const __str_literal_7("pc = 0x%x", 9u);


/* Constructor */
MOD_mkProcessor::MOD_mkProcessor(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycles(simHdl, "cycles", this, 32u, 0u, (tUInt8)0u),
    INST_d2e(simHdl, "d2e", this, 158u, 2u, (tUInt8)1u, 0u),
    INST_dmemReqQ(simHdl, "dmemReqQ", this, 51u, 2u, (tUInt8)1u, 0u),
    INST_dmemRespQ(simHdl, "dmemRespQ", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_e2m(simHdl, "e2m", this, 73u, 2u, (tUInt8)1u, 0u),
    INST_f2d(simHdl, "f2d", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_imemReqQ(simHdl, "imemReqQ", this, 51u, 2u, (tUInt8)1u, 0u),
    INST_imemRespQ(simHdl, "imemRespQ", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_instCnt(simHdl, "instCnt", this, 32u, 0u, (tUInt8)0u),
    INST_pc(simHdl, "pc", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_0(simHdl, "rf_rfile_0", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_1(simHdl, "rf_rfile_1", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_10(simHdl, "rf_rfile_10", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_11(simHdl, "rf_rfile_11", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_12(simHdl, "rf_rfile_12", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_13(simHdl, "rf_rfile_13", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_14(simHdl, "rf_rfile_14", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_15(simHdl, "rf_rfile_15", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_16(simHdl, "rf_rfile_16", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_17(simHdl, "rf_rfile_17", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_18(simHdl, "rf_rfile_18", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_19(simHdl, "rf_rfile_19", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_2(simHdl, "rf_rfile_2", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_20(simHdl, "rf_rfile_20", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_21(simHdl, "rf_rfile_21", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_22(simHdl, "rf_rfile_22", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_23(simHdl, "rf_rfile_23", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_24(simHdl, "rf_rfile_24", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_25(simHdl, "rf_rfile_25", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_26(simHdl, "rf_rfile_26", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_27(simHdl, "rf_rfile_27", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_28(simHdl, "rf_rfile_28", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_29(simHdl, "rf_rfile_29", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_3(simHdl, "rf_rfile_3", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_30(simHdl, "rf_rfile_30", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_31(simHdl, "rf_rfile_31", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_4(simHdl, "rf_rfile_4", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_5(simHdl, "rf_rfile_5", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_6(simHdl, "rf_rfile_6", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_7(simHdl, "rf_rfile_7", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_8(simHdl, "rf_rfile_8", this, 32u, 0u, (tUInt8)0u),
    INST_rf_rfile_9(simHdl, "rf_rfile_9", this, 32u, 0u, (tUInt8)0u),
    INST_stage(simHdl, "stage", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_d2e_first____d293(158u),
    DEF_e2m_first____d439(73u),
    DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432(73u),
    DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431(73u),
    DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428(73u),
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434(73u),
    DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427(73u),
    DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290(158u)
{
  symbol_count = 48u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkProcessor::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycles", SYM_MODULE, &INST_cycles);
  init_symbol(&symbols[1u], "d2e", SYM_MODULE, &INST_d2e);
  init_symbol(&symbols[2u], "dmemReqQ", SYM_MODULE, &INST_dmemReqQ);
  init_symbol(&symbols[3u], "dmemRespQ", SYM_MODULE, &INST_dmemRespQ);
  init_symbol(&symbols[4u], "e2m", SYM_MODULE, &INST_e2m);
  init_symbol(&symbols[5u], "f2d", SYM_MODULE, &INST_f2d);
  init_symbol(&symbols[6u], "imemReqQ", SYM_MODULE, &INST_imemReqQ);
  init_symbol(&symbols[7u], "imemRespQ", SYM_MODULE, &INST_imemRespQ);
  init_symbol(&symbols[8u], "instCnt", SYM_MODULE, &INST_instCnt);
  init_symbol(&symbols[9u], "pc", SYM_MODULE, &INST_pc);
  init_symbol(&symbols[10u], "RL_doDecode", SYM_RULE);
  init_symbol(&symbols[11u], "RL_doExecute", SYM_RULE);
  init_symbol(&symbols[12u], "RL_doFetch", SYM_RULE);
  init_symbol(&symbols[13u], "RL_doWriteback", SYM_RULE);
  init_symbol(&symbols[14u], "RL_incCycle", SYM_RULE);
  init_symbol(&symbols[15u], "rf_rfile_0", SYM_MODULE, &INST_rf_rfile_0);
  init_symbol(&symbols[16u], "rf_rfile_1", SYM_MODULE, &INST_rf_rfile_1);
  init_symbol(&symbols[17u], "rf_rfile_10", SYM_MODULE, &INST_rf_rfile_10);
  init_symbol(&symbols[18u], "rf_rfile_11", SYM_MODULE, &INST_rf_rfile_11);
  init_symbol(&symbols[19u], "rf_rfile_12", SYM_MODULE, &INST_rf_rfile_12);
  init_symbol(&symbols[20u], "rf_rfile_13", SYM_MODULE, &INST_rf_rfile_13);
  init_symbol(&symbols[21u], "rf_rfile_14", SYM_MODULE, &INST_rf_rfile_14);
  init_symbol(&symbols[22u], "rf_rfile_15", SYM_MODULE, &INST_rf_rfile_15);
  init_symbol(&symbols[23u], "rf_rfile_16", SYM_MODULE, &INST_rf_rfile_16);
  init_symbol(&symbols[24u], "rf_rfile_17", SYM_MODULE, &INST_rf_rfile_17);
  init_symbol(&symbols[25u], "rf_rfile_18", SYM_MODULE, &INST_rf_rfile_18);
  init_symbol(&symbols[26u], "rf_rfile_19", SYM_MODULE, &INST_rf_rfile_19);
  init_symbol(&symbols[27u], "rf_rfile_2", SYM_MODULE, &INST_rf_rfile_2);
  init_symbol(&symbols[28u], "rf_rfile_20", SYM_MODULE, &INST_rf_rfile_20);
  init_symbol(&symbols[29u], "rf_rfile_21", SYM_MODULE, &INST_rf_rfile_21);
  init_symbol(&symbols[30u], "rf_rfile_22", SYM_MODULE, &INST_rf_rfile_22);
  init_symbol(&symbols[31u], "rf_rfile_23", SYM_MODULE, &INST_rf_rfile_23);
  init_symbol(&symbols[32u], "rf_rfile_24", SYM_MODULE, &INST_rf_rfile_24);
  init_symbol(&symbols[33u], "rf_rfile_25", SYM_MODULE, &INST_rf_rfile_25);
  init_symbol(&symbols[34u], "rf_rfile_26", SYM_MODULE, &INST_rf_rfile_26);
  init_symbol(&symbols[35u], "rf_rfile_27", SYM_MODULE, &INST_rf_rfile_27);
  init_symbol(&symbols[36u], "rf_rfile_28", SYM_MODULE, &INST_rf_rfile_28);
  init_symbol(&symbols[37u], "rf_rfile_29", SYM_MODULE, &INST_rf_rfile_29);
  init_symbol(&symbols[38u], "rf_rfile_3", SYM_MODULE, &INST_rf_rfile_3);
  init_symbol(&symbols[39u], "rf_rfile_30", SYM_MODULE, &INST_rf_rfile_30);
  init_symbol(&symbols[40u], "rf_rfile_31", SYM_MODULE, &INST_rf_rfile_31);
  init_symbol(&symbols[41u], "rf_rfile_4", SYM_MODULE, &INST_rf_rfile_4);
  init_symbol(&symbols[42u], "rf_rfile_5", SYM_MODULE, &INST_rf_rfile_5);
  init_symbol(&symbols[43u], "rf_rfile_6", SYM_MODULE, &INST_rf_rfile_6);
  init_symbol(&symbols[44u], "rf_rfile_7", SYM_MODULE, &INST_rf_rfile_7);
  init_symbol(&symbols[45u], "rf_rfile_8", SYM_MODULE, &INST_rf_rfile_8);
  init_symbol(&symbols[46u], "rf_rfile_9", SYM_MODULE, &INST_rf_rfile_9);
  init_symbol(&symbols[47u], "stage", SYM_MODULE, &INST_stage);
}


/* Rule actions */

void MOD_mkProcessor::RL_incCycle()
{
  tUInt32 DEF_x__h98;
  DEF_x__h118 = INST_cycles.METH_read();
  DEF_x__h98 = DEF_x__h118 + 1u;
  INST_cycles.METH_write(DEF_x__h98);
}

void MOD_mkProcessor::RL_doFetch()
{
  tUInt64 DEF_pc_BITS_15_TO_0_0_CONCAT_DONTCARE_CONCAT_6___d11;
  tUInt32 DEF_x_addr__h2912;
  tUInt32 DEF_x__h2918;
  DEF_x__h6520 = INST_instCnt.METH_read();
  DEF_x__h118 = INST_cycles.METH_read();
  DEF_x__h2918 = INST_pc.METH_read();
  DEF_x_addr__h2912 = (tUInt32)(65535u & DEF_x__h2918);
  DEF_pc_BITS_15_TO_0_0_CONCAT_DONTCARE_CONCAT_6___d11 = 2251799813685247llu & ((((tUInt64)(DEF_x_addr__h2912)) << 35u) | 22906492246llu);
  INST_imemReqQ.METH_enq(DEF_pc_BITS_15_TO_0_0_CONCAT_DONTCARE_CONCAT_6___d11);
  INST_f2d.METH_enq(DEF_x__h2918);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_write(sim_hdl,
		 this,
		 "s,32,32,32",
		 &__str_literal_1,
		 DEF_x__h118,
		 DEF_x__h2918,
		 DEF_x__h6520);
  INST_stage.METH_write((tUInt8)1u);
}

void MOD_mkProcessor::RL_doDecode()
{
  tUInt32 DEF_x__h4632;
  tUInt32 DEF_x__h4426;
  tUInt32 DEF_x__h4538;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d140;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1_3_ETC___d240;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d245;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b111___d32;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b110___d31;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b100___d30;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b11___d29;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d45;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d42;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d56;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d78;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d74;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d65;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d47;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d163;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d143;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d184;
  tUInt8 DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b100000___d43;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d142;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d162;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d183;
  tUInt8 DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d147;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d167;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d191;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d174;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d173;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d153;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d187;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d171;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d165;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d145;
  tUInt8 DEF_x__h4163;
  tUInt8 DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d186;
  tUInt8 DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33;
  tUInt32 DEF_immB__h3096;
  tUInt32 DEF_immS__h3095;
  tUInt8 DEF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11___d69;
  tUInt32 DEF_immI__h3094;
  tUInt32 DEF_immJ__h3098;
  tUInt32 DEF_immU__h3097;
  tUInt32 DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d203;
  tUInt32 DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231;
  tUInt32 DEF_dInst_imm__h3676;
  tUInt32 DEF_x__h6093;
  tUInt32 DEF_x__h5074;
  tUInt8 DEF_imemRespQ_first__1_BIT_31___d204;
  tUInt8 DEF_funct3__h3088;
  tUInt8 DEF_dst__h3090;
  tUInt8 DEF_src1__h3091;
  tUInt8 DEF_src2__h3092;
  tUInt8 DEF_opcode__h3087;
  tUInt8 DEF_funct7__h3089;
  tUInt32 DEF_x__h4391;
  tUInt32 DEF_f2d_first____d20;
  tUInt32 DEF_imemRespQ_first____d21;
  tUInt32 DEF__read__h1083;
  tUInt32 DEF__read__h1114;
  tUInt32 DEF__read__h1145;
  tUInt32 DEF__read__h1176;
  tUInt32 DEF__read__h1207;
  tUInt32 DEF__read__h1238;
  tUInt32 DEF__read__h1269;
  tUInt32 DEF__read__h1300;
  tUInt32 DEF__read__h1331;
  tUInt32 DEF__read__h1362;
  tUInt32 DEF__read__h1393;
  tUInt32 DEF__read__h1424;
  tUInt32 DEF__read__h1455;
  tUInt32 DEF__read__h1486;
  tUInt32 DEF__read__h1517;
  tUInt32 DEF__read__h1548;
  tUInt32 DEF__read__h1579;
  tUInt32 DEF__read__h1610;
  tUInt32 DEF__read__h1641;
  tUInt32 DEF__read__h1672;
  tUInt32 DEF__read__h1703;
  tUInt32 DEF__read__h1734;
  tUInt32 DEF__read__h1765;
  tUInt32 DEF__read__h1796;
  tUInt32 DEF__read__h1827;
  tUInt32 DEF__read__h1858;
  tUInt32 DEF__read__h1889;
  tUInt32 DEF__read__h1920;
  tUInt32 DEF__read__h1951;
  tUInt32 DEF__read__h1982;
  tUInt32 DEF__read__h2013;
  tUInt32 DEF__read__h2044;
  tUInt8 DEF_x__h4285;
  tUInt8 DEF_x__h4220;
  DEF__read__h2044 = INST_rf_rfile_31.METH_read();
  DEF__read__h2013 = INST_rf_rfile_30.METH_read();
  DEF__read__h1982 = INST_rf_rfile_29.METH_read();
  DEF__read__h1951 = INST_rf_rfile_28.METH_read();
  DEF__read__h1920 = INST_rf_rfile_27.METH_read();
  DEF__read__h1889 = INST_rf_rfile_26.METH_read();
  DEF__read__h1858 = INST_rf_rfile_25.METH_read();
  DEF__read__h1765 = INST_rf_rfile_22.METH_read();
  DEF__read__h1827 = INST_rf_rfile_24.METH_read();
  DEF__read__h1734 = INST_rf_rfile_21.METH_read();
  DEF__read__h1796 = INST_rf_rfile_23.METH_read();
  DEF__read__h1703 = INST_rf_rfile_20.METH_read();
  DEF__read__h1672 = INST_rf_rfile_19.METH_read();
  DEF__read__h1610 = INST_rf_rfile_17.METH_read();
  DEF__read__h1641 = INST_rf_rfile_18.METH_read();
  DEF__read__h1579 = INST_rf_rfile_16.METH_read();
  DEF__read__h1548 = INST_rf_rfile_15.METH_read();
  DEF__read__h1517 = INST_rf_rfile_14.METH_read();
  DEF__read__h1486 = INST_rf_rfile_13.METH_read();
  DEF__read__h1455 = INST_rf_rfile_12.METH_read();
  DEF__read__h1424 = INST_rf_rfile_11.METH_read();
  DEF__read__h1331 = INST_rf_rfile_8.METH_read();
  DEF__read__h1393 = INST_rf_rfile_10.METH_read();
  DEF__read__h1300 = INST_rf_rfile_7.METH_read();
  DEF__read__h1362 = INST_rf_rfile_9.METH_read();
  DEF__read__h1269 = INST_rf_rfile_6.METH_read();
  DEF__read__h1238 = INST_rf_rfile_5.METH_read();
  DEF__read__h1207 = INST_rf_rfile_4.METH_read();
  DEF__read__h1114 = INST_rf_rfile_1.METH_read();
  DEF__read__h1176 = INST_rf_rfile_3.METH_read();
  DEF__read__h1083 = INST_rf_rfile_0.METH_read();
  DEF__read__h1145 = INST_rf_rfile_2.METH_read();
  DEF_imemRespQ_first____d21 = INST_imemRespQ.METH_first();
  DEF_f2d_first____d20 = INST_f2d.METH_first();
  DEF_x__h118 = INST_cycles.METH_read();
  DEF_x__h4391 = (tUInt32)(DEF_imemRespQ_first____d21 >> 20u);
  DEF_funct7__h3089 = (tUInt8)(DEF_imemRespQ_first____d21 >> 25u);
  DEF_opcode__h3087 = (tUInt8)((tUInt8)127u & DEF_imemRespQ_first____d21);
  DEF_src2__h3092 = (tUInt8)((tUInt8)31u & (DEF_imemRespQ_first____d21 >> 20u));
  DEF_src1__h3091 = (tUInt8)((tUInt8)31u & (DEF_imemRespQ_first____d21 >> 15u));
  DEF_dst__h3090 = (tUInt8)((tUInt8)31u & (DEF_imemRespQ_first____d21 >> 7u));
  DEF_imemRespQ_first__1_BIT_31___d204 = (tUInt8)(DEF_imemRespQ_first____d21 >> 31u);
  DEF_funct3__h3088 = (tUInt8)((tUInt8)7u & (DEF_imemRespQ_first____d21 >> 12u));
  DEF_immU__h3097 = ((tUInt32)(DEF_imemRespQ_first____d21 >> 12u)) << 12u;
  DEF_immI__h3094 = primSignExt32(32u, 12u, (tUInt32)(DEF_x__h4391));
  switch (DEF_funct3__h3088) {
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d203 = DEF_immI__h3094;
  }
  DEF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11___d69 = DEF_opcode__h3087 == (tUInt8)3u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33 = DEF_funct3__h3088 == (tUInt8)1u;
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d171 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d171 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d187 = DEF_src2__h3092;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d187 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)4u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d153 = DEF_dst__h3090;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d153 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)4u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d173 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d173 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d191 = DEF_src2__h3092;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d191 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d174 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d174 = (tUInt8)0u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d167 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d167 = (tUInt8)0u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d147 = DEF_dst__h3090;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d147 = (tUInt8)0u;
  }
  DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 = DEF_funct7__h3089 == (tUInt8)0u;
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150 = DEF_dst__h3090;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150 = DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? DEF_dst__h3090 : (tUInt8)0u;
    break;
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d147;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170 = DEF_src1__h3091;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170 = DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? DEF_src1__h3091 : (tUInt8)0u;
    break;
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d167;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d183 = DEF_src2__h3092;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d183 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d162 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d162 = (tUInt8)0u;
  }
  DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b100000___d43 = DEF_funct7__h3089 == (tUInt8)32u;
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d142 = DEF_dst__h3090;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d142 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d184 = DEF_src2__h3092;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d184 = (tUInt8)0u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d186 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d183;
    break;
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d186 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d184;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d186 = (tUInt8)0u;
  }
  switch (DEF_opcode__h3087) {
  case (tUInt8)51u:
    DEF_x__h4285 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d186;
    break;
  case (tUInt8)99u:
    DEF_x__h4285 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d187;
    break;
  case (tUInt8)35u:
    DEF_x__h4285 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d191;
    break;
  default:
    DEF_x__h4285 = (tUInt8)0u;
  }
  switch (DEF_x__h4285) {
  case (tUInt8)0u:
    DEF_x__h6093 = DEF__read__h1083;
    break;
  case (tUInt8)1u:
    DEF_x__h6093 = DEF__read__h1114;
    break;
  case (tUInt8)2u:
    DEF_x__h6093 = DEF__read__h1145;
    break;
  case (tUInt8)3u:
    DEF_x__h6093 = DEF__read__h1176;
    break;
  case (tUInt8)4u:
    DEF_x__h6093 = DEF__read__h1207;
    break;
  case (tUInt8)5u:
    DEF_x__h6093 = DEF__read__h1238;
    break;
  case (tUInt8)6u:
    DEF_x__h6093 = DEF__read__h1269;
    break;
  case (tUInt8)7u:
    DEF_x__h6093 = DEF__read__h1300;
    break;
  case (tUInt8)8u:
    DEF_x__h6093 = DEF__read__h1331;
    break;
  case (tUInt8)9u:
    DEF_x__h6093 = DEF__read__h1362;
    break;
  case (tUInt8)10u:
    DEF_x__h6093 = DEF__read__h1393;
    break;
  case (tUInt8)11u:
    DEF_x__h6093 = DEF__read__h1424;
    break;
  case (tUInt8)12u:
    DEF_x__h6093 = DEF__read__h1455;
    break;
  case (tUInt8)13u:
    DEF_x__h6093 = DEF__read__h1486;
    break;
  case (tUInt8)14u:
    DEF_x__h6093 = DEF__read__h1517;
    break;
  case (tUInt8)15u:
    DEF_x__h6093 = DEF__read__h1548;
    break;
  case (tUInt8)16u:
    DEF_x__h6093 = DEF__read__h1579;
    break;
  case (tUInt8)17u:
    DEF_x__h6093 = DEF__read__h1610;
    break;
  case (tUInt8)18u:
    DEF_x__h6093 = DEF__read__h1641;
    break;
  case (tUInt8)19u:
    DEF_x__h6093 = DEF__read__h1672;
    break;
  case (tUInt8)20u:
    DEF_x__h6093 = DEF__read__h1703;
    break;
  case (tUInt8)21u:
    DEF_x__h6093 = DEF__read__h1734;
    break;
  case (tUInt8)22u:
    DEF_x__h6093 = DEF__read__h1765;
    break;
  case (tUInt8)23u:
    DEF_x__h6093 = DEF__read__h1796;
    break;
  case (tUInt8)24u:
    DEF_x__h6093 = DEF__read__h1827;
    break;
  case (tUInt8)25u:
    DEF_x__h6093 = DEF__read__h1858;
    break;
  case (tUInt8)26u:
    DEF_x__h6093 = DEF__read__h1889;
    break;
  case (tUInt8)27u:
    DEF_x__h6093 = DEF__read__h1920;
    break;
  case (tUInt8)28u:
    DEF_x__h6093 = DEF__read__h1951;
    break;
  case (tUInt8)29u:
    DEF_x__h6093 = DEF__read__h1982;
    break;
  case (tUInt8)30u:
    DEF_x__h6093 = DEF__read__h2013;
    break;
  case (tUInt8)31u:
    DEF_x__h6093 = DEF__read__h2044;
    break;
  default:
    DEF_x__h6093 = 2863311530u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d143 = DEF_dst__h3090;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d143 = (tUInt8)0u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d145 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d142;
    break;
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d145 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d143;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d145 = (tUInt8)0u;
  }
  switch (DEF_opcode__h3087) {
  case (tUInt8)51u:
    DEF_x__h4163 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d145;
    break;
  case (tUInt8)19u:
    DEF_x__h4163 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d150;
    break;
  case (tUInt8)23u:
  case (tUInt8)55u:
  case (tUInt8)103u:
  case (tUInt8)111u:
    DEF_x__h4163 = DEF_dst__h3090;
    break;
  case (tUInt8)3u:
    DEF_x__h4163 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d153;
    break;
  default:
    DEF_x__h4163 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d163 = DEF_src1__h3091;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d163 = (tUInt8)0u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d165 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d162;
    break;
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d165 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d163;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d165 = (tUInt8)0u;
  }
  switch (DEF_opcode__h3087) {
  case (tUInt8)51u:
    DEF_x__h4220 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d165;
    break;
  case (tUInt8)19u:
    DEF_x__h4220 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d170;
    break;
  case (tUInt8)99u:
    DEF_x__h4220 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d171;
    break;
  case (tUInt8)103u:
    DEF_x__h4220 = DEF_src1__h3091;
    break;
  case (tUInt8)3u:
    DEF_x__h4220 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d173;
    break;
  case (tUInt8)35u:
    DEF_x__h4220 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d174;
    break;
  default:
    DEF_x__h4220 = (tUInt8)0u;
  }
  switch (DEF_x__h4220) {
  case (tUInt8)0u:
    DEF_x__h5074 = DEF__read__h1083;
    break;
  case (tUInt8)1u:
    DEF_x__h5074 = DEF__read__h1114;
    break;
  case (tUInt8)2u:
    DEF_x__h5074 = DEF__read__h1145;
    break;
  case (tUInt8)3u:
    DEF_x__h5074 = DEF__read__h1176;
    break;
  case (tUInt8)4u:
    DEF_x__h5074 = DEF__read__h1207;
    break;
  case (tUInt8)5u:
    DEF_x__h5074 = DEF__read__h1238;
    break;
  case (tUInt8)6u:
    DEF_x__h5074 = DEF__read__h1269;
    break;
  case (tUInt8)7u:
    DEF_x__h5074 = DEF__read__h1300;
    break;
  case (tUInt8)8u:
    DEF_x__h5074 = DEF__read__h1331;
    break;
  case (tUInt8)9u:
    DEF_x__h5074 = DEF__read__h1362;
    break;
  case (tUInt8)10u:
    DEF_x__h5074 = DEF__read__h1393;
    break;
  case (tUInt8)11u:
    DEF_x__h5074 = DEF__read__h1424;
    break;
  case (tUInt8)12u:
    DEF_x__h5074 = DEF__read__h1455;
    break;
  case (tUInt8)13u:
    DEF_x__h5074 = DEF__read__h1486;
    break;
  case (tUInt8)14u:
    DEF_x__h5074 = DEF__read__h1517;
    break;
  case (tUInt8)15u:
    DEF_x__h5074 = DEF__read__h1548;
    break;
  case (tUInt8)16u:
    DEF_x__h5074 = DEF__read__h1579;
    break;
  case (tUInt8)17u:
    DEF_x__h5074 = DEF__read__h1610;
    break;
  case (tUInt8)18u:
    DEF_x__h5074 = DEF__read__h1641;
    break;
  case (tUInt8)19u:
    DEF_x__h5074 = DEF__read__h1672;
    break;
  case (tUInt8)20u:
    DEF_x__h5074 = DEF__read__h1703;
    break;
  case (tUInt8)21u:
    DEF_x__h5074 = DEF__read__h1734;
    break;
  case (tUInt8)22u:
    DEF_x__h5074 = DEF__read__h1765;
    break;
  case (tUInt8)23u:
    DEF_x__h5074 = DEF__read__h1796;
    break;
  case (tUInt8)24u:
    DEF_x__h5074 = DEF__read__h1827;
    break;
  case (tUInt8)25u:
    DEF_x__h5074 = DEF__read__h1858;
    break;
  case (tUInt8)26u:
    DEF_x__h5074 = DEF__read__h1889;
    break;
  case (tUInt8)27u:
    DEF_x__h5074 = DEF__read__h1920;
    break;
  case (tUInt8)28u:
    DEF_x__h5074 = DEF__read__h1951;
    break;
  case (tUInt8)29u:
    DEF_x__h5074 = DEF__read__h1982;
    break;
  case (tUInt8)30u:
    DEF_x__h5074 = DEF__read__h2013;
    break;
  case (tUInt8)31u:
    DEF_x__h5074 = DEF__read__h2044;
    break;
  default:
    DEF_x__h5074 = 2863311530u;
  }
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34 = DEF_funct3__h3088 == (tUInt8)5u;
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)0u;
    break;
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)5u;
    break;
  case (tUInt8)3u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)6u;
    break;
  case (tUInt8)4u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)4u;
    break;
  case (tUInt8)6u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)3u;
    break;
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)2u;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = (tUInt8)7u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111 = DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? (tUInt8)8u : (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d65 = (tUInt8)2u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d65 = (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)4u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d74 = (tUInt8)6u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d74 = (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d78 = (tUInt8)7u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d78 = (tUInt8)9u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d56 = (tUInt8)1u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d56 = (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59 = (tUInt8)1u;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59 = DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? (tUInt8)1u : (tUInt8)9u;
    break;
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d56;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59 = (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)0u;
    break;
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)5u;
    break;
  case (tUInt8)3u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)6u;
    break;
  case (tUInt8)4u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)4u;
    break;
  case (tUInt8)6u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)3u;
    break;
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)2u;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)7u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 = (tUInt8)8u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d42 = (tUInt8)0u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d42 = (tUInt8)9u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d45 = (tUInt8)0u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d45 = (tUInt8)9u;
  }
  switch (DEF_funct7__h3089) {
  case (tUInt8)0u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d47 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d42;
    break;
  case (tUInt8)32u:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d47 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d45;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d47 = (tUInt8)9u;
  }
  switch (DEF_opcode__h3087) {
  case (tUInt8)51u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = DEF_IF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0_5_ETC___d47;
    break;
  case (tUInt8)19u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d59;
    break;
  case (tUInt8)99u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d65;
    break;
  case (tUInt8)55u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = (tUInt8)3u;
    break;
  case (tUInt8)111u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = (tUInt8)4u;
    break;
  case (tUInt8)103u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = (tUInt8)5u;
    break;
  case (tUInt8)3u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d74;
    break;
  case (tUInt8)35u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d78;
    break;
  case (tUInt8)23u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = (tUInt8)8u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88 = (tUInt8)9u;
  }
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 = DEF_funct3__h3088 == (tUInt8)0u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28 = DEF_funct3__h3088 == (tUInt8)2u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b11___d29 = DEF_funct3__h3088 == (tUInt8)3u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b100___d30 = DEF_funct3__h3088 == (tUInt8)4u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b111___d32 = DEF_funct3__h3088 == (tUInt8)7u;
  DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b110___d31 = DEF_funct3__h3088 == (tUInt8)6u;
  switch (DEF_funct3__h3088) {
  case (tUInt8)0u:
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120 = DEF_funct3__h3088;
    break;
  case (tUInt8)4u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120 = (tUInt8)2u;
    break;
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120 = (tUInt8)4u;
    break;
  case (tUInt8)6u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120 = (tUInt8)3u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120 = (tUInt8)5u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)2u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d245 = (tUInt8)3u;
    break;
  case (tUInt8)1u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d245 = (tUInt8)1u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d245 = (tUInt8)0u;
  }
  switch (DEF_funct3__h3088) {
  case (tUInt8)1u:
  case (tUInt8)5u:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1_3_ETC___d240 = (tUInt8)1u;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1_3_ETC___d240 = (tUInt8)0u;
  }
  switch (DEF_opcode__h3087) {
  case (tUInt8)51u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d140 = DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b11___d29 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b100___d30 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b110___d31 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b111___d32 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33 || DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34)))))) : DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b100000___d43 && (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 || DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34);
    break;
  case (tUInt8)19u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d140 = DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b11___d29 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b100___d30 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b110___d31 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b111___d32 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33 ? DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 : DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34 && (DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 || DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b100000___d43)))))));
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d140 = !(DEF_opcode__h3087 == (tUInt8)99u) && (DEF_opcode__h3087 == (tUInt8)55u || (DEF_opcode__h3087 == (tUInt8)111u || (DEF_opcode__h3087 == (tUInt8)103u || (DEF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11___d69 ? DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 || (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b101___d34 || DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b100___d30))) : DEF_opcode__h3087 == (tUInt8)23u))));
  }
  DEF_x__h4538 = 2097151u & (((((((tUInt32)(DEF_imemRespQ_first__1_BIT_31___d204)) << 20u) | (((tUInt32)((tUInt8)((tUInt8)255u & (DEF_imemRespQ_first____d21 >> 12u)))) << 12u)) | (((tUInt32)((tUInt8)((tUInt8)1u & (DEF_imemRespQ_first____d21 >> 20u)))) << 11u)) | (((tUInt32)(1023u & (DEF_imemRespQ_first____d21 >> 21u))) << 1u)) | (tUInt32)((tUInt8)0u));
  DEF_immJ__h3098 = primSignExt32(32u, 21u, (tUInt32)(DEF_x__h4538));
  DEF_x__h4426 = 8191u & (((((((tUInt32)(DEF_imemRespQ_first__1_BIT_31___d204)) << 12u) | (((tUInt32)((tUInt8)((tUInt8)1u & (DEF_imemRespQ_first____d21 >> 7u)))) << 11u)) | (((tUInt32)((tUInt8)((tUInt8)63u & (DEF_imemRespQ_first____d21 >> 25u)))) << 5u)) | (((tUInt32)((tUInt8)((tUInt8)15u & (DEF_imemRespQ_first____d21 >> 8u)))) << 1u)) | (tUInt32)((tUInt8)0u));
  DEF_immB__h3096 = primSignExt32(32u, 13u, (tUInt32)(DEF_x__h4426));
  DEF_x__h4632 = 4095u & ((((tUInt32)(DEF_funct7__h3089)) << 5u) | (tUInt32)(DEF_dst__h3090));
  DEF_immS__h3095 = primSignExt32(32u, 12u, (tUInt32)(DEF_x__h4632));
  switch (DEF_opcode__h3087) {
  case (tUInt8)19u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d203;
    break;
  case (tUInt8)99u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_immB__h3096;
    break;
  case (tUInt8)111u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_immJ__h3098;
    break;
  case (tUInt8)3u:
  case (tUInt8)103u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_immI__h3094;
    break;
  case (tUInt8)35u:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_immS__h3095;
    break;
  default:
    DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231 = DEF_immU__h3097;
  }
  DEF_dInst_imm__h3676 = DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b10011_ETC___d231;
  DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290.set_bits_in_word((tUInt32)(DEF_f2d_first____d20 >> 2u),
										 4u,
										 0u,
										 30u).set_whole_word(((((((((((tUInt32)((tUInt8)((tUInt8)3u & DEF_f2d_first____d20))) << 30u) | (((tUInt32)(DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d88)) << 26u)) | (((tUInt32)(DEF_opcode__h3087 == (tUInt8)51u ? (DEF_imemRespQ_first__1_BITS_31_TO_25_4_EQ_0b0___d25 ? DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d96 : (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27 ? (tUInt8)1u : (tUInt8)9u)) : DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d111)) << 22u)) | (((tUInt32)(DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0_7_ETC___d120)) << 19u)) | (((tUInt32)(DEF_IF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11001_ETC___d140)) << 18u)) | (((tUInt32)(DEF_x__h4163)) << 13u)) | (((tUInt32)(DEF_x__h4220)) << 8u)) | (((tUInt32)(DEF_x__h4285)) << 3u)) | (tUInt32)((tUInt8)(DEF_dInst_imm__h3676 >> 29u)),
												     3u).build_concat(bs_wide_tmp(96u).build_concat((tUInt32)(536870911u & DEF_dInst_imm__h3676),
																		    67u,
																		    29u).set_bits_in_word(DEF_imemRespQ_first__1_BITS_6_TO_0_2_EQ_0b11___d69 ? (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10___d28 ? (tUInt8)6u : (tUInt8)7u & ((DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1_3_ETC___d240 << 1u) | (DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b1___d33 || DEF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b0___d27))) : (tUInt8)7u & (DEF_IF_imemRespQ_first__1_BITS_14_TO_12_6_EQ_0b10__ETC___d245 << 1u),
																					  2u,
																					  0u,
																					  3u).set_whole_word(DEF_x__h5074,
																							     1u).set_whole_word(DEF_x__h6093,
																										0u),
														      0u,
														      96u);
  INST_f2d.METH_deq();
  INST_imemRespQ.METH_deq();
  INST_d2e.METH_enq(DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290);
  INST_stage.METH_write((tUInt8)2u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_write(sim_hdl,
		 this,
		 "s,32,32,32",
		 &__str_literal_2,
		 DEF_x__h118,
		 DEF_f2d_first____d20,
		 DEF_imemRespQ_first____d21);
}

void MOD_mkProcessor::RL_doExecute()
{
  tUInt64 DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_0_05_OR_ETC___d422;
  tUInt64 DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424;
  tUInt32 DEF_x__h6510;
  tUInt8 DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348;
  tUInt8 DEF_d2e_first__93_BITS_63_TO_32_13_EQ_d2e_first__9_ETC___d315;
  tUInt8 DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d437;
  tUInt32 DEF_eInst_data__h6248;
  tUInt8 DEF_d2e_first__93_BITS_63_TO_32_13_SLT_d2e_first___ETC___d319;
  tUInt8 DEF_d2e_first__93_BITS_63_TO_32_13_ULT_d2e_first___ETC___d321;
  tUInt8 DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332;
  tUInt32 DEF_nextPc__h6466;
  tUInt32 DEF_nextPc__h6330;
  tUInt32 DEF_x__h6221;
  tUInt32 DEF_nextPc__h6235;
  tUInt8 DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_OR_d2_ETC___d349;
  tUInt32 DEF_data__h6328;
  tUInt32 DEF_data__h6326;
  tUInt32 DEF_d2e_first__93_BITS_157_TO_126_08_PLUS_d2e_firs_ETC___d334;
  tUInt8 DEF_d2e_first__93_BIT_114___d429;
  tUInt8 DEF_x_bytes__h6837;
  tUInt8 DEF_d2e_first__93_BITS_117_TO_115___d311;
  tUInt8 DEF_d2e_first__93_BITS_121_TO_118___d358;
  tUInt8 DEF_d2e_first__93_BITS_4_TO_0___d374;
  tUInt8 DEF_d2e_first__93_BITS_71_TO_67___d396;
  tUInt8 DEF_x_dst__h7360;
  tUInt32 DEF_eInst_addr__h6249;
  tUInt32 DEF_x_addr__h6835;
  tUInt32 DEF_addr__h6482;
  tUInt32 DEF_rVal2__h6209;
  tUInt32 DEF_rVal1__h6208;
  tUInt32 DEF_imm__h6231;
  tUInt32 DEF_d2e_first__93_BITS_157_TO_126___d308;
  DEF_d2e_first____d293 = INST_d2e.METH_first();
  DEF_x__h6520 = INST_instCnt.METH_read();
  DEF_x__h118 = INST_cycles.METH_read();
  DEF_d2e_first__93_BITS_157_TO_126___d308 = primExtract32(32u,
							   158u,
							   DEF_d2e_first____d293,
							   32u,
							   157u,
							   32u,
							   126u);
  DEF_imm__h6231 = primExtract32(32u, 158u, DEF_d2e_first____d293, 32u, 98u, 32u, 67u);
  DEF_rVal1__h6208 = DEF_d2e_first____d293.get_whole_word(1u);
  DEF_rVal2__h6209 = DEF_d2e_first____d293.get_whole_word(0u);
  DEF_addr__h6482 = DEF_rVal1__h6208 + DEF_imm__h6231;
  DEF_x_dst__h7360 = DEF_d2e_first____d293.get_bits_in_word8(3u, 13u, 5u);
  DEF_d2e_first__93_BITS_71_TO_67___d396 = DEF_d2e_first____d293.get_bits_in_word8(2u, 3u, 5u);
  DEF_d2e_first__93_BITS_4_TO_0___d374 = DEF_d2e_first____d293.get_bits_in_word8(0u, 0u, 5u);
  DEF_d2e_first__93_BITS_125_TO_122___d294 = DEF_d2e_first____d293.get_bits_in_word8(3u, 26u, 4u);
  switch (DEF_d2e_first__93_BITS_125_TO_122___d294) {
  case (tUInt8)6u:
  case (tUInt8)7u:
    DEF_eInst_addr__h6249 = DEF_addr__h6482;
    break;
  default:
    DEF_eInst_addr__h6249 = 0u;
  }
  DEF_x_addr__h6835 = (tUInt32)(65535u & DEF_eInst_addr__h6249);
  DEF_d2e_first__93_BITS_121_TO_118___d358 = DEF_d2e_first____d293.get_bits_in_word8(3u, 22u, 4u);
  DEF_d2e_first__93_BITS_117_TO_115___d311 = DEF_d2e_first____d293.get_bits_in_word8(3u, 19u, 3u);
  DEF_x_bytes__h6837 = DEF_d2e_first____d293.get_bits_in_word8(2u, 1u, 2u);
  DEF_d2e_first__93_BIT_114___d429 = DEF_d2e_first____d293.get_bits_in_word8(3u, 18u, 1u);
  DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428.set_bits_in_word((tUInt32)(DEF_d2e_first__93_BITS_157_TO_126___d308 >> 23u),
										 2u,
										 0u,
										 9u).set_whole_word((((tUInt32)(8388607u & DEF_d2e_first__93_BITS_157_TO_126___d308)) << 9u) | (tUInt32)(11453246122llu >> 32u),
												    1u).set_whole_word((tUInt32)(11453246122llu),
														       0u);
  DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295 = DEF_d2e_first__93_BITS_125_TO_122___d294 == (tUInt8)6u;
  DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297 = DEF_d2e_first__93_BITS_125_TO_122___d294 == (tUInt8)7u;
  DEF_d2e_first__93_BITS_157_TO_126_08_PLUS_d2e_firs_ETC___d334 = DEF_d2e_first__93_BITS_157_TO_126___d308 + DEF_imm__h6231;
  switch (DEF_d2e_first__93_BITS_121_TO_118___d358) {
  case (tUInt8)0u:
    DEF_data__h6328 = DEF_addr__h6482;
    break;
  case (tUInt8)1u:
    DEF_data__h6328 = DEF_rVal1__h6208 - DEF_imm__h6231;
    break;
  case (tUInt8)2u:
    DEF_data__h6328 = DEF_rVal1__h6208 & DEF_imm__h6231;
    break;
  case (tUInt8)3u:
    DEF_data__h6328 = DEF_rVal1__h6208 | DEF_imm__h6231;
    break;
  case (tUInt8)4u:
    DEF_data__h6328 = DEF_rVal1__h6208 ^ DEF_imm__h6231;
    break;
  case (tUInt8)5u:
    DEF_data__h6328 = primSLT8(1u,
			       32u,
			       (tUInt32)(DEF_rVal1__h6208),
			       32u,
			       (tUInt32)(DEF_imm__h6231)) ? 1u : 0u;
    break;
  case (tUInt8)6u:
    DEF_data__h6328 = DEF_rVal1__h6208 < DEF_imm__h6231 ? 1u : 0u;
    break;
  case (tUInt8)7u:
    DEF_data__h6328 = primShiftL32(32u,
				   32u,
				   (tUInt32)(DEF_rVal1__h6208),
				   5u,
				   (tUInt8)(DEF_d2e_first__93_BITS_71_TO_67___d396));
    break;
  case (tUInt8)8u:
    DEF_data__h6328 = primShiftR32(32u,
				   32u,
				   (tUInt32)(DEF_rVal1__h6208),
				   5u,
				   (tUInt8)(DEF_d2e_first__93_BITS_71_TO_67___d396));
    break;
  default:
    DEF_data__h6328 = primShiftRA32(32u,
				    32u,
				    (tUInt32)(DEF_rVal1__h6208),
				    5u,
				    (tUInt8)(DEF_d2e_first__93_BITS_71_TO_67___d396));
  }
  DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_OR_d2_ETC___d349 = DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295 || DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297;
  DEF_nextPc__h6235 = DEF_d2e_first__93_BITS_157_TO_126___d308 + 4u;
  DEF_nextPc__h6466 = (((tUInt32)(DEF_addr__h6482 >> 1u)) << 1u) | (tUInt32)((tUInt8)0u);
  DEF_d2e_first__93_BITS_63_TO_32_13_ULT_d2e_first___ETC___d321 = DEF_rVal1__h6208 < DEF_rVal2__h6209;
  DEF_d2e_first__93_BITS_63_TO_32_13_SLT_d2e_first___ETC___d319 = primSLT8(1u,
									   32u,
									   (tUInt32)(DEF_rVal1__h6208),
									   32u,
									   (tUInt32)(DEF_rVal2__h6209));
  switch (DEF_d2e_first__93_BITS_121_TO_118___d358) {
  case (tUInt8)0u:
    DEF_data__h6326 = DEF_rVal1__h6208 + DEF_rVal2__h6209;
    break;
  case (tUInt8)1u:
    DEF_data__h6326 = DEF_rVal1__h6208 - DEF_rVal2__h6209;
    break;
  case (tUInt8)2u:
    DEF_data__h6326 = DEF_rVal1__h6208 & DEF_rVal2__h6209;
    break;
  case (tUInt8)3u:
    DEF_data__h6326 = DEF_rVal1__h6208 | DEF_rVal2__h6209;
    break;
  case (tUInt8)4u:
    DEF_data__h6326 = DEF_rVal1__h6208 ^ DEF_rVal2__h6209;
    break;
  case (tUInt8)5u:
    DEF_data__h6326 = DEF_d2e_first__93_BITS_63_TO_32_13_SLT_d2e_first___ETC___d319 ? 1u : 0u;
    break;
  case (tUInt8)6u:
    DEF_data__h6326 = DEF_d2e_first__93_BITS_63_TO_32_13_ULT_d2e_first___ETC___d321 ? 1u : 0u;
    break;
  case (tUInt8)7u:
    DEF_data__h6326 = primShiftL32(32u,
				   32u,
				   (tUInt32)(DEF_rVal1__h6208),
				   5u,
				   (tUInt8)(DEF_d2e_first__93_BITS_4_TO_0___d374));
    break;
  case (tUInt8)8u:
    DEF_data__h6326 = primShiftR32(32u,
				   32u,
				   (tUInt32)(DEF_rVal1__h6208),
				   5u,
				   (tUInt8)(DEF_d2e_first__93_BITS_4_TO_0___d374));
    break;
  default:
    DEF_data__h6326 = primShiftRA32(32u,
				    32u,
				    (tUInt32)(DEF_rVal1__h6208),
				    5u,
				    (tUInt8)(DEF_d2e_first__93_BITS_4_TO_0___d374));
  }
  switch (DEF_d2e_first__93_BITS_125_TO_122___d294) {
  case (tUInt8)0u:
    DEF_eInst_data__h6248 = DEF_data__h6326;
    break;
  case (tUInt8)1u:
    DEF_eInst_data__h6248 = DEF_data__h6328;
    break;
  case (tUInt8)3u:
    DEF_eInst_data__h6248 = DEF_imm__h6231;
    break;
  case (tUInt8)4u:
  case (tUInt8)5u:
    DEF_eInst_data__h6248 = DEF_nextPc__h6235;
    break;
  case (tUInt8)7u:
    DEF_eInst_data__h6248 = DEF_rVal2__h6209;
    break;
  default:
    DEF_eInst_data__h6248 = DEF_d2e_first__93_BITS_157_TO_126_08_PLUS_d2e_firs_ETC___d334;
  }
  switch (DEF_d2e_first__93_BITS_125_TO_122___d294) {
  case (tUInt8)6u:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d437 = (tUInt8)3u;
    break;
  case (tUInt8)7u:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d437 = (tUInt8)0u;
    break;
  default:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d437 = DEF_d2e_first__93_BIT_114___d429 ? (tUInt8)3u : (tUInt8)0u;
  }
  DEF_d2e_first__93_BITS_63_TO_32_13_EQ_d2e_first__9_ETC___d315 = DEF_rVal1__h6208 == DEF_rVal2__h6209;
  switch (DEF_d2e_first__93_BITS_117_TO_115___d311) {
  case (tUInt8)0u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = DEF_d2e_first__93_BITS_63_TO_32_13_EQ_d2e_first__9_ETC___d315;
    break;
  case (tUInt8)1u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = !DEF_d2e_first__93_BITS_63_TO_32_13_EQ_d2e_first__9_ETC___d315;
    break;
  case (tUInt8)2u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = DEF_d2e_first__93_BITS_63_TO_32_13_SLT_d2e_first___ETC___d319;
    break;
  case (tUInt8)3u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = DEF_d2e_first__93_BITS_63_TO_32_13_ULT_d2e_first___ETC___d321;
    break;
  case (tUInt8)4u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = !DEF_d2e_first__93_BITS_63_TO_32_13_SLT_d2e_first___ETC___d319;
    break;
  case (tUInt8)5u:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = !DEF_d2e_first__93_BITS_63_TO_32_13_ULT_d2e_first___ETC___d321;
    break;
  default:
    DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 = DEF_d2e_first__93_BITS_117_TO_115___d311 == (tUInt8)6u;
  }
  DEF_nextPc__h6330 = DEF_IF_d2e_first__93_BITS_117_TO_115_11_EQ_0_12_TH_ETC___d332 ? DEF_d2e_first__93_BITS_157_TO_126_08_PLUS_d2e_firs_ETC___d334 : DEF_nextPc__h6235;
  switch (DEF_d2e_first__93_BITS_125_TO_122___d294) {
  case (tUInt8)2u:
    DEF_x__h6221 = DEF_nextPc__h6330;
    break;
  case (tUInt8)4u:
    DEF_x__h6221 = DEF_d2e_first__93_BITS_157_TO_126_08_PLUS_d2e_firs_ETC___d334;
    break;
  case (tUInt8)5u:
    DEF_x__h6221 = DEF_nextPc__h6466;
    break;
  default:
    DEF_x__h6221 = DEF_nextPc__h6235;
  }
  DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348 = DEF_d2e_first__93_BITS_125_TO_122___d294 == (tUInt8)9u;
  DEF_x__h6510 = DEF_x__h6520 + 1u;
  DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424 = 137438953471llu & ((((tUInt64)(DEF_d2e_first__93_BITS_157_TO_126___d308)) << 5u) | (tUInt64)(DEF_x_dst__h7360));
  DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431.set_bits_in_word((tUInt32)(DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424 >> 28u),
										 2u,
										 0u,
										 9u).set_whole_word(((((tUInt32)(268435455u & DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424)) << 4u) | (((tUInt32)((tUInt8)0u)) << 3u)) | (tUInt32)((tUInt8)(DEF_eInst_data__h6248 >> 29u)),
												    1u).set_whole_word((((tUInt32)(536870911u & DEF_eInst_data__h6248)) << 3u) | (tUInt32)((tUInt8)2u),
														       0u);
  DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432 = DEF_d2e_first__93_BIT_114___d429 ? DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431 : DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428;
  DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427.set_bits_in_word((tUInt32)(DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424 >> 28u),
										 2u,
										 0u,
										 9u).set_whole_word((((tUInt32)(268435455u & DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d424)) << 4u) | (tUInt32)((tUInt8)(4294967296llu >> 29u)),
												    1u).set_whole_word(((((tUInt32)(536870911u & 4294967296llu)) << 3u) | (((tUInt32)(DEF_d2e_first____d293.get_bits_in_word8(2u,
																											      0u,
																											      1u))) << 2u)) | (tUInt32)(DEF_x_bytes__h6837),
														       0u);
  switch (DEF_d2e_first__93_BITS_125_TO_122___d294) {
  case (tUInt8)6u:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427;
    break;
  case (tUInt8)7u:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428;
    break;
  default:
    DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434 = DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432;
  }
  INST_d2e.METH_deq();
  DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_0_05_OR_ETC___d422 = 2251799813685247llu & ((((((tUInt64)(DEF_x_addr__h6835)) << 35u) | (((tUInt64)(DEF_eInst_data__h6248)) << 3u)) | (((tUInt64)(DEF_x_bytes__h6837)) << 1u)) | (tUInt64)(!DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295));
  INST_pc.METH_write(DEF_x__h6221);
  INST_instCnt.METH_write(DEF_x__h6510);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_write(sim_hdl,
		 this,
		 "s,32,32",
		 &__str_literal_3,
		 DEF_x__h118,
		 DEF_d2e_first__93_BITS_157_TO_126___d308);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_display(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_display(sim_hdl, this, "s,32,32", &__str_literal_5, DEF_x__h118, DEF_x__h6520);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_display(sim_hdl, this, "s", &__str_literal_6);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_7, DEF_d2e_first__93_BITS_157_TO_126___d308);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_display(sim_hdl, this, "s", &__str_literal_8);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_9___d348)
      dollar_finish(sim_hdl, "32", 1u);
  }
  if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_OR_d2_ETC___d349)
    INST_dmemReqQ.METH_enq(DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_0_05_OR_ETC___d422);
  INST_e2m.METH_enq(DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434);
  INST_stage.METH_write(DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d437);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295)
      dollar_write(sim_hdl,
		   this,
		   "s,32,32,32",
		   &__str_literal_9,
		   DEF_x__h118,
		   DEF_d2e_first__93_BITS_157_TO_126___d308,
		   DEF_eInst_addr__h6249);
    if (DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297)
      dollar_write(sim_hdl,
		   this,
		   "s,32,32,32,32",
		   &__str_literal_10,
		   DEF_x__h118,
		   DEF_d2e_first__93_BITS_157_TO_126___d308,
		   DEF_eInst_data__h6248,
		   DEF_eInst_addr__h6249);
  }
}

void MOD_mkProcessor::RL_doWriteback()
{
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_1___d465;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_2___d466;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_3___d467;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_4___d468;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_5___d469;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_6___d470;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_7___d471;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_8___d472;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_9___d473;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_10___d474;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_11___d475;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_12___d476;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_13___d477;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_14___d478;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_15___d479;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_16___d480;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_17___d481;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_18___d482;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_19___d483;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_20___d484;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_21___d485;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_22___d486;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_23___d487;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_24___d488;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_25___d489;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_26___d490;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_27___d491;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_28___d492;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_29___d493;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_30___d494;
  tUInt8 DEF_e2m_first__39_BITS_40_TO_36_64_EQ_31___d495;
  tUInt32 DEF_v__h7646;
  tUInt32 DEF_dw___1__h7801;
  tUInt32 DEF_dw___1__h7776;
  tUInt32 DEF_dw___1__h7745;
  tUInt32 DEF_dw___1__h7719;
  tUInt32 DEF_v__h7675;
  tUInt8 DEF_e2m_first__39_BIT_2___d449;
  tUInt8 DEF_x__h7748;
  tUInt32 DEF_x__h7804;
  tUInt32 DEF_dw__h7642;
  tUInt32 DEF_e2m_first__39_BITS_72_TO_41___d496;
  tUInt32 DEF_dmemRespQ_first____d450;
  tUInt8 DEF_rindx__h7847;
  DEF_e2m_first____d439 = INST_e2m.METH_first();
  DEF_rindx__h7847 = DEF_e2m_first____d439.get_bits_in_word8(1u, 4u, 5u);
  DEF_dmemRespQ_first____d450 = INST_dmemRespQ.METH_first();
  DEF_x__h118 = INST_cycles.METH_read();
  DEF_dw__h7642 = primExtract32(32u, 73u, DEF_e2m_first____d439, 32u, 34u, 32u, 3u);
  DEF_e2m_first__39_BITS_72_TO_41___d496 = primExtract32(32u,
							 73u,
							 DEF_e2m_first____d439,
							 32u,
							 72u,
							 32u,
							 41u);
  DEF_x__h7804 = (tUInt32)(65535u & DEF_dmemRespQ_first____d450);
  DEF_x__h7748 = (tUInt8)((tUInt8)255u & DEF_dmemRespQ_first____d450);
  DEF_e2m_first__39_BIT_35___d440 = DEF_e2m_first____d439.get_bits_in_word8(1u, 3u, 1u);
  DEF_e2m_first__39_BIT_2___d449 = DEF_e2m_first____d439.get_bits_in_word8(0u, 2u, 1u);
  DEF_dw___1__h7719 = primSignExt32(32u, 8u, (tUInt8)(DEF_x__h7748));
  DEF_dw___1__h7776 = primSignExt32(32u, 16u, (tUInt32)(DEF_x__h7804));
  DEF_dw___1__h7745 = (tUInt32)(DEF_x__h7748);
  DEF_dw___1__h7801 = DEF_x__h7804;
  switch (DEF_e2m_first____d439.get_bits_in_word8(0u, 0u, 2u)) {
  case (tUInt8)0u:
    DEF_v__h7675 = DEF_e2m_first__39_BIT_2___d449 ? DEF_dw___1__h7719 : DEF_dw___1__h7745;
    break;
  case (tUInt8)1u:
    DEF_v__h7675 = DEF_e2m_first__39_BIT_2___d449 ? DEF_dw___1__h7776 : DEF_dw___1__h7801;
    break;
  default:
    DEF_v__h7675 = DEF_dmemRespQ_first____d450;
  }
  DEF_v__h7646 = DEF_e2m_first__39_BIT_35___d440 ? DEF_v__h7675 : DEF_dw__h7642;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_31___d495 = DEF_rindx__h7847 == (tUInt8)31u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_30___d494 = DEF_rindx__h7847 == (tUInt8)30u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_29___d493 = DEF_rindx__h7847 == (tUInt8)29u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_28___d492 = DEF_rindx__h7847 == (tUInt8)28u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_27___d491 = DEF_rindx__h7847 == (tUInt8)27u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_26___d490 = DEF_rindx__h7847 == (tUInt8)26u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_25___d489 = DEF_rindx__h7847 == (tUInt8)25u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_24___d488 = DEF_rindx__h7847 == (tUInt8)24u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_23___d487 = DEF_rindx__h7847 == (tUInt8)23u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_21___d485 = DEF_rindx__h7847 == (tUInt8)21u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_22___d486 = DEF_rindx__h7847 == (tUInt8)22u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_20___d484 = DEF_rindx__h7847 == (tUInt8)20u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_19___d483 = DEF_rindx__h7847 == (tUInt8)19u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_18___d482 = DEF_rindx__h7847 == (tUInt8)18u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_17___d481 = DEF_rindx__h7847 == (tUInt8)17u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_16___d480 = DEF_rindx__h7847 == (tUInt8)16u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_15___d479 = DEF_rindx__h7847 == (tUInt8)15u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_13___d477 = DEF_rindx__h7847 == (tUInt8)13u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_14___d478 = DEF_rindx__h7847 == (tUInt8)14u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_12___d476 = DEF_rindx__h7847 == (tUInt8)12u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_11___d475 = DEF_rindx__h7847 == (tUInt8)11u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_10___d474 = DEF_rindx__h7847 == (tUInt8)10u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_9___d473 = DEF_rindx__h7847 == (tUInt8)9u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_8___d472 = DEF_rindx__h7847 == (tUInt8)8u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_7___d471 = DEF_rindx__h7847 == (tUInt8)7u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_6___d470 = DEF_rindx__h7847 == (tUInt8)6u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_5___d469 = DEF_rindx__h7847 == (tUInt8)5u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_3___d467 = DEF_rindx__h7847 == (tUInt8)3u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_4___d468 = DEF_rindx__h7847 == (tUInt8)4u;
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_2___d466 = DEF_rindx__h7847 == (tUInt8)2u;
  INST_e2m.METH_deq();
  DEF_e2m_first__39_BITS_40_TO_36_64_EQ_1___d465 = DEF_rindx__h7847 == (tUInt8)1u;
  if (DEF_e2m_first__39_BIT_35___d440)
    INST_dmemRespQ.METH_deq();
  
  /* dead code removed here */
  ;
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_1___d465)
    INST_rf_rfile_1.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_2___d466)
    INST_rf_rfile_2.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_3___d467)
    INST_rf_rfile_3.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_4___d468)
    INST_rf_rfile_4.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_6___d470)
    INST_rf_rfile_6.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_5___d469)
    INST_rf_rfile_5.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_7___d471)
    INST_rf_rfile_7.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_8___d472)
    INST_rf_rfile_8.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_9___d473)
    INST_rf_rfile_9.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_11___d475)
    INST_rf_rfile_11.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_10___d474)
    INST_rf_rfile_10.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_12___d476)
    INST_rf_rfile_12.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_13___d477)
    INST_rf_rfile_13.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_14___d478)
    INST_rf_rfile_14.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_15___d479)
    INST_rf_rfile_15.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_16___d480)
    INST_rf_rfile_16.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_17___d481)
    INST_rf_rfile_17.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_18___d482)
    INST_rf_rfile_18.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_19___d483)
    INST_rf_rfile_19.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_20___d484)
    INST_rf_rfile_20.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_21___d485)
    INST_rf_rfile_21.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_22___d486)
    INST_rf_rfile_22.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_23___d487)
    INST_rf_rfile_23.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_24___d488)
    INST_rf_rfile_24.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_26___d490)
    INST_rf_rfile_26.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_25___d489)
    INST_rf_rfile_25.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_27___d491)
    INST_rf_rfile_27.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_28___d492)
    INST_rf_rfile_28.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_29___d493)
    INST_rf_rfile_29.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_30___d494)
    INST_rf_rfile_30.METH_write(DEF_v__h7646);
  if (DEF_e2m_first__39_BITS_40_TO_36_64_EQ_31___d495)
    INST_rf_rfile_31.METH_write(DEF_v__h7646);
  INST_stage.METH_write((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_write(sim_hdl,
		 this,
		 "s,32,32,32,5",
		 &__str_literal_11,
		 DEF_x__h118,
		 DEF_e2m_first__39_BITS_72_TO_41___d496,
		 DEF_v__h7646,
		 DEF_rindx__h7847);
}


/* Methods */

tUInt64 MOD_mkProcessor::METH_iMemReq()
{
  tUInt64 DEF_iMemReq__avValue1;
  tUInt64 PORT_iMemReq;
  DEF_iMemReq__avValue1 = INST_imemReqQ.METH_first();
  PORT_iMemReq = DEF_iMemReq__avValue1;
  INST_imemReqQ.METH_deq();
  return PORT_iMemReq;
}

tUInt8 MOD_mkProcessor::METH_RDY_iMemReq()
{
  tUInt8 PORT_RDY_iMemReq;
  tUInt8 DEF_CAN_FIRE_iMemReq;
  DEF_CAN_FIRE_iMemReq = INST_imemReqQ.METH_i_notEmpty();
  PORT_RDY_iMemReq = DEF_CAN_FIRE_iMemReq;
  return PORT_RDY_iMemReq;
}

void MOD_mkProcessor::METH_iMemResp(tUInt32 ARG_iMemResp_data)
{
  INST_imemRespQ.METH_enq(ARG_iMemResp_data);
}

tUInt8 MOD_mkProcessor::METH_RDY_iMemResp()
{
  tUInt8 PORT_RDY_iMemResp;
  tUInt8 DEF_CAN_FIRE_iMemResp;
  DEF_CAN_FIRE_iMemResp = INST_imemRespQ.METH_i_notFull();
  PORT_RDY_iMemResp = DEF_CAN_FIRE_iMemResp;
  return PORT_RDY_iMemResp;
}

tUInt64 MOD_mkProcessor::METH_dMemReq()
{
  tUInt64 DEF_dMemReq__avValue2;
  tUInt64 PORT_dMemReq;
  DEF_dMemReq__avValue2 = INST_dmemReqQ.METH_first();
  PORT_dMemReq = DEF_dMemReq__avValue2;
  INST_dmemReqQ.METH_deq();
  return PORT_dMemReq;
}

tUInt8 MOD_mkProcessor::METH_RDY_dMemReq()
{
  tUInt8 PORT_RDY_dMemReq;
  tUInt8 DEF_CAN_FIRE_dMemReq;
  DEF_CAN_FIRE_dMemReq = INST_dmemReqQ.METH_i_notEmpty();
  PORT_RDY_dMemReq = DEF_CAN_FIRE_dMemReq;
  return PORT_RDY_dMemReq;
}

void MOD_mkProcessor::METH_dMemResp(tUInt32 ARG_dMemResp_data)
{
  INST_dmemRespQ.METH_enq(ARG_dMemResp_data);
}

tUInt8 MOD_mkProcessor::METH_RDY_dMemResp()
{
  tUInt8 PORT_RDY_dMemResp;
  tUInt8 DEF_CAN_FIRE_dMemResp;
  DEF_CAN_FIRE_dMemResp = INST_dmemRespQ.METH_i_notFull();
  PORT_RDY_dMemResp = DEF_CAN_FIRE_dMemResp;
  return PORT_RDY_dMemResp;
}


/* Reset routines */

void MOD_mkProcessor::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_stage.reset_RST(ARG_rst_in);
  INST_rf_rfile_9.reset_RST(ARG_rst_in);
  INST_rf_rfile_8.reset_RST(ARG_rst_in);
  INST_rf_rfile_7.reset_RST(ARG_rst_in);
  INST_rf_rfile_6.reset_RST(ARG_rst_in);
  INST_rf_rfile_5.reset_RST(ARG_rst_in);
  INST_rf_rfile_4.reset_RST(ARG_rst_in);
  INST_rf_rfile_31.reset_RST(ARG_rst_in);
  INST_rf_rfile_30.reset_RST(ARG_rst_in);
  INST_rf_rfile_3.reset_RST(ARG_rst_in);
  INST_rf_rfile_29.reset_RST(ARG_rst_in);
  INST_rf_rfile_28.reset_RST(ARG_rst_in);
  INST_rf_rfile_27.reset_RST(ARG_rst_in);
  INST_rf_rfile_26.reset_RST(ARG_rst_in);
  INST_rf_rfile_25.reset_RST(ARG_rst_in);
  INST_rf_rfile_24.reset_RST(ARG_rst_in);
  INST_rf_rfile_23.reset_RST(ARG_rst_in);
  INST_rf_rfile_22.reset_RST(ARG_rst_in);
  INST_rf_rfile_21.reset_RST(ARG_rst_in);
  INST_rf_rfile_20.reset_RST(ARG_rst_in);
  INST_rf_rfile_2.reset_RST(ARG_rst_in);
  INST_rf_rfile_19.reset_RST(ARG_rst_in);
  INST_rf_rfile_18.reset_RST(ARG_rst_in);
  INST_rf_rfile_17.reset_RST(ARG_rst_in);
  INST_rf_rfile_16.reset_RST(ARG_rst_in);
  INST_rf_rfile_15.reset_RST(ARG_rst_in);
  INST_rf_rfile_14.reset_RST(ARG_rst_in);
  INST_rf_rfile_13.reset_RST(ARG_rst_in);
  INST_rf_rfile_12.reset_RST(ARG_rst_in);
  INST_rf_rfile_11.reset_RST(ARG_rst_in);
  INST_rf_rfile_10.reset_RST(ARG_rst_in);
  INST_rf_rfile_1.reset_RST(ARG_rst_in);
  INST_rf_rfile_0.reset_RST(ARG_rst_in);
  INST_pc.reset_RST(ARG_rst_in);
  INST_instCnt.reset_RST(ARG_rst_in);
  INST_imemRespQ.reset_RST(ARG_rst_in);
  INST_imemReqQ.reset_RST(ARG_rst_in);
  INST_f2d.reset_RST(ARG_rst_in);
  INST_e2m.reset_RST(ARG_rst_in);
  INST_dmemRespQ.reset_RST(ARG_rst_in);
  INST_dmemReqQ.reset_RST(ARG_rst_in);
  INST_d2e.reset_RST(ARG_rst_in);
  INST_cycles.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkProcessor::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkProcessor::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycles.dump_state(indent + 2u);
  INST_d2e.dump_state(indent + 2u);
  INST_dmemReqQ.dump_state(indent + 2u);
  INST_dmemRespQ.dump_state(indent + 2u);
  INST_e2m.dump_state(indent + 2u);
  INST_f2d.dump_state(indent + 2u);
  INST_imemReqQ.dump_state(indent + 2u);
  INST_imemRespQ.dump_state(indent + 2u);
  INST_instCnt.dump_state(indent + 2u);
  INST_pc.dump_state(indent + 2u);
  INST_rf_rfile_0.dump_state(indent + 2u);
  INST_rf_rfile_1.dump_state(indent + 2u);
  INST_rf_rfile_10.dump_state(indent + 2u);
  INST_rf_rfile_11.dump_state(indent + 2u);
  INST_rf_rfile_12.dump_state(indent + 2u);
  INST_rf_rfile_13.dump_state(indent + 2u);
  INST_rf_rfile_14.dump_state(indent + 2u);
  INST_rf_rfile_15.dump_state(indent + 2u);
  INST_rf_rfile_16.dump_state(indent + 2u);
  INST_rf_rfile_17.dump_state(indent + 2u);
  INST_rf_rfile_18.dump_state(indent + 2u);
  INST_rf_rfile_19.dump_state(indent + 2u);
  INST_rf_rfile_2.dump_state(indent + 2u);
  INST_rf_rfile_20.dump_state(indent + 2u);
  INST_rf_rfile_21.dump_state(indent + 2u);
  INST_rf_rfile_22.dump_state(indent + 2u);
  INST_rf_rfile_23.dump_state(indent + 2u);
  INST_rf_rfile_24.dump_state(indent + 2u);
  INST_rf_rfile_25.dump_state(indent + 2u);
  INST_rf_rfile_26.dump_state(indent + 2u);
  INST_rf_rfile_27.dump_state(indent + 2u);
  INST_rf_rfile_28.dump_state(indent + 2u);
  INST_rf_rfile_29.dump_state(indent + 2u);
  INST_rf_rfile_3.dump_state(indent + 2u);
  INST_rf_rfile_30.dump_state(indent + 2u);
  INST_rf_rfile_31.dump_state(indent + 2u);
  INST_rf_rfile_4.dump_state(indent + 2u);
  INST_rf_rfile_5.dump_state(indent + 2u);
  INST_rf_rfile_6.dump_state(indent + 2u);
  INST_rf_rfile_7.dump_state(indent + 2u);
  INST_rf_rfile_8.dump_state(indent + 2u);
  INST_rf_rfile_9.dump_state(indent + 2u);
  INST_stage.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkProcessor::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 58u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434", 73u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432", 73u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_125_TO_122_94_EQ_6___d295", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_125_TO_122_94_EQ_7___d297", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_125_TO_122___d294", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428", 73u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427", 73u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431", 73u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "d2e_first____d293", 158u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "e2m_first__39_BIT_35___d440", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "e2m_first____d439", 73u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290", 158u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h118", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h6520", 32u);
  num = INST_cycles.dump_VCD_defs(num);
  num = INST_d2e.dump_VCD_defs(num);
  num = INST_dmemReqQ.dump_VCD_defs(num);
  num = INST_dmemRespQ.dump_VCD_defs(num);
  num = INST_e2m.dump_VCD_defs(num);
  num = INST_f2d.dump_VCD_defs(num);
  num = INST_imemReqQ.dump_VCD_defs(num);
  num = INST_imemRespQ.dump_VCD_defs(num);
  num = INST_instCnt.dump_VCD_defs(num);
  num = INST_pc.dump_VCD_defs(num);
  num = INST_rf_rfile_0.dump_VCD_defs(num);
  num = INST_rf_rfile_1.dump_VCD_defs(num);
  num = INST_rf_rfile_10.dump_VCD_defs(num);
  num = INST_rf_rfile_11.dump_VCD_defs(num);
  num = INST_rf_rfile_12.dump_VCD_defs(num);
  num = INST_rf_rfile_13.dump_VCD_defs(num);
  num = INST_rf_rfile_14.dump_VCD_defs(num);
  num = INST_rf_rfile_15.dump_VCD_defs(num);
  num = INST_rf_rfile_16.dump_VCD_defs(num);
  num = INST_rf_rfile_17.dump_VCD_defs(num);
  num = INST_rf_rfile_18.dump_VCD_defs(num);
  num = INST_rf_rfile_19.dump_VCD_defs(num);
  num = INST_rf_rfile_2.dump_VCD_defs(num);
  num = INST_rf_rfile_20.dump_VCD_defs(num);
  num = INST_rf_rfile_21.dump_VCD_defs(num);
  num = INST_rf_rfile_22.dump_VCD_defs(num);
  num = INST_rf_rfile_23.dump_VCD_defs(num);
  num = INST_rf_rfile_24.dump_VCD_defs(num);
  num = INST_rf_rfile_25.dump_VCD_defs(num);
  num = INST_rf_rfile_26.dump_VCD_defs(num);
  num = INST_rf_rfile_27.dump_VCD_defs(num);
  num = INST_rf_rfile_28.dump_VCD_defs(num);
  num = INST_rf_rfile_29.dump_VCD_defs(num);
  num = INST_rf_rfile_3.dump_VCD_defs(num);
  num = INST_rf_rfile_30.dump_VCD_defs(num);
  num = INST_rf_rfile_31.dump_VCD_defs(num);
  num = INST_rf_rfile_4.dump_VCD_defs(num);
  num = INST_rf_rfile_5.dump_VCD_defs(num);
  num = INST_rf_rfile_6.dump_VCD_defs(num);
  num = INST_rf_rfile_7.dump_VCD_defs(num);
  num = INST_rf_rfile_8.dump_VCD_defs(num);
  num = INST_rf_rfile_9.dump_VCD_defs(num);
  num = INST_stage.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkProcessor::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkProcessor &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkProcessor::vcd_defs(tVCDDumpType dt, MOD_mkProcessor &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 158u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 158u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434) != DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434, 73u);
	backing.DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434 = DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434;
      }
      ++num;
      if ((backing.DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432) != DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432, 73u);
	backing.DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432 = DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295) != DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295, 1u);
	backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295 = DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297) != DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297, 1u);
	backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297 = DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_125_TO_122___d294) != DEF_d2e_first__93_BITS_125_TO_122___d294)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_125_TO_122___d294, 4u);
	backing.DEF_d2e_first__93_BITS_125_TO_122___d294 = DEF_d2e_first__93_BITS_125_TO_122___d294;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428) != DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428, 73u);
	backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427) != DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427, 73u);
	backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427;
      }
      ++num;
      if ((backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431) != DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431, 73u);
	backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431;
      }
      ++num;
      if ((backing.DEF_d2e_first____d293) != DEF_d2e_first____d293)
      {
	vcd_write_val(sim_hdl, num, DEF_d2e_first____d293, 158u);
	backing.DEF_d2e_first____d293 = DEF_d2e_first____d293;
      }
      ++num;
      if ((backing.DEF_e2m_first__39_BIT_35___d440) != DEF_e2m_first__39_BIT_35___d440)
      {
	vcd_write_val(sim_hdl, num, DEF_e2m_first__39_BIT_35___d440, 1u);
	backing.DEF_e2m_first__39_BIT_35___d440 = DEF_e2m_first__39_BIT_35___d440;
      }
      ++num;
      if ((backing.DEF_e2m_first____d439) != DEF_e2m_first____d439)
      {
	vcd_write_val(sim_hdl, num, DEF_e2m_first____d439, 73u);
	backing.DEF_e2m_first____d439 = DEF_e2m_first____d439;
      }
      ++num;
      if ((backing.DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290) != DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290)
      {
	vcd_write_val(sim_hdl, num, DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290, 158u);
	backing.DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290 = DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290;
      }
      ++num;
      if ((backing.DEF_x__h118) != DEF_x__h118)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h118, 32u);
	backing.DEF_x__h118 = DEF_x__h118;
      }
      ++num;
      if ((backing.DEF_x__h6520) != DEF_x__h6520)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h6520, 32u);
	backing.DEF_x__h6520 = DEF_x__h6520;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434, 73u);
      backing.DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434 = DEF_IF_d2e_first__93_BITS_125_TO_122_94_EQ_6_95_TH_ETC___d434;
      vcd_write_val(sim_hdl, num++, DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432, 73u);
      backing.DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432 = DEF_IF_d2e_first__93_BIT_114_29_THEN_d2e_first__93_ETC___d432;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295, 1u);
      backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295 = DEF_d2e_first__93_BITS_125_TO_122_94_EQ_6___d295;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297, 1u);
      backing.DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297 = DEF_d2e_first__93_BITS_125_TO_122_94_EQ_7___d297;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_125_TO_122___d294, 4u);
      backing.DEF_d2e_first__93_BITS_125_TO_122___d294 = DEF_d2e_first__93_BITS_125_TO_122___d294;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428, 73u);
      backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_0_CONC_ETC___d428;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427, 73u);
      backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d427;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431, 73u);
      backing.DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431 = DEF_d2e_first__93_BITS_157_TO_126_08_CONCAT_d2e_fi_ETC___d431;
      vcd_write_val(sim_hdl, num++, DEF_d2e_first____d293, 158u);
      backing.DEF_d2e_first____d293 = DEF_d2e_first____d293;
      vcd_write_val(sim_hdl, num++, DEF_e2m_first__39_BIT_35___d440, 1u);
      backing.DEF_e2m_first__39_BIT_35___d440 = DEF_e2m_first__39_BIT_35___d440;
      vcd_write_val(sim_hdl, num++, DEF_e2m_first____d439, 73u);
      backing.DEF_e2m_first____d439 = DEF_e2m_first____d439;
      vcd_write_val(sim_hdl, num++, DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290, 158u);
      backing.DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290 = DEF_f2d_first__0_CONCAT_IF_imemRespQ_first__1_BITS_ETC___d290;
      vcd_write_val(sim_hdl, num++, DEF_x__h118, 32u);
      backing.DEF_x__h118 = DEF_x__h118;
      vcd_write_val(sim_hdl, num++, DEF_x__h6520, 32u);
      backing.DEF_x__h6520 = DEF_x__h6520;
    }
}

void MOD_mkProcessor::vcd_prims(tVCDDumpType dt, MOD_mkProcessor &backing)
{
  INST_cycles.dump_VCD(dt, backing.INST_cycles);
  INST_d2e.dump_VCD(dt, backing.INST_d2e);
  INST_dmemReqQ.dump_VCD(dt, backing.INST_dmemReqQ);
  INST_dmemRespQ.dump_VCD(dt, backing.INST_dmemRespQ);
  INST_e2m.dump_VCD(dt, backing.INST_e2m);
  INST_f2d.dump_VCD(dt, backing.INST_f2d);
  INST_imemReqQ.dump_VCD(dt, backing.INST_imemReqQ);
  INST_imemRespQ.dump_VCD(dt, backing.INST_imemRespQ);
  INST_instCnt.dump_VCD(dt, backing.INST_instCnt);
  INST_pc.dump_VCD(dt, backing.INST_pc);
  INST_rf_rfile_0.dump_VCD(dt, backing.INST_rf_rfile_0);
  INST_rf_rfile_1.dump_VCD(dt, backing.INST_rf_rfile_1);
  INST_rf_rfile_10.dump_VCD(dt, backing.INST_rf_rfile_10);
  INST_rf_rfile_11.dump_VCD(dt, backing.INST_rf_rfile_11);
  INST_rf_rfile_12.dump_VCD(dt, backing.INST_rf_rfile_12);
  INST_rf_rfile_13.dump_VCD(dt, backing.INST_rf_rfile_13);
  INST_rf_rfile_14.dump_VCD(dt, backing.INST_rf_rfile_14);
  INST_rf_rfile_15.dump_VCD(dt, backing.INST_rf_rfile_15);
  INST_rf_rfile_16.dump_VCD(dt, backing.INST_rf_rfile_16);
  INST_rf_rfile_17.dump_VCD(dt, backing.INST_rf_rfile_17);
  INST_rf_rfile_18.dump_VCD(dt, backing.INST_rf_rfile_18);
  INST_rf_rfile_19.dump_VCD(dt, backing.INST_rf_rfile_19);
  INST_rf_rfile_2.dump_VCD(dt, backing.INST_rf_rfile_2);
  INST_rf_rfile_20.dump_VCD(dt, backing.INST_rf_rfile_20);
  INST_rf_rfile_21.dump_VCD(dt, backing.INST_rf_rfile_21);
  INST_rf_rfile_22.dump_VCD(dt, backing.INST_rf_rfile_22);
  INST_rf_rfile_23.dump_VCD(dt, backing.INST_rf_rfile_23);
  INST_rf_rfile_24.dump_VCD(dt, backing.INST_rf_rfile_24);
  INST_rf_rfile_25.dump_VCD(dt, backing.INST_rf_rfile_25);
  INST_rf_rfile_26.dump_VCD(dt, backing.INST_rf_rfile_26);
  INST_rf_rfile_27.dump_VCD(dt, backing.INST_rf_rfile_27);
  INST_rf_rfile_28.dump_VCD(dt, backing.INST_rf_rfile_28);
  INST_rf_rfile_29.dump_VCD(dt, backing.INST_rf_rfile_29);
  INST_rf_rfile_3.dump_VCD(dt, backing.INST_rf_rfile_3);
  INST_rf_rfile_30.dump_VCD(dt, backing.INST_rf_rfile_30);
  INST_rf_rfile_31.dump_VCD(dt, backing.INST_rf_rfile_31);
  INST_rf_rfile_4.dump_VCD(dt, backing.INST_rf_rfile_4);
  INST_rf_rfile_5.dump_VCD(dt, backing.INST_rf_rfile_5);
  INST_rf_rfile_6.dump_VCD(dt, backing.INST_rf_rfile_6);
  INST_rf_rfile_7.dump_VCD(dt, backing.INST_rf_rfile_7);
  INST_rf_rfile_8.dump_VCD(dt, backing.INST_rf_rfile_8);
  INST_rf_rfile_9.dump_VCD(dt, backing.INST_rf_rfile_9);
  INST_stage.dump_VCD(dt, backing.INST_stage);
}
