/*
 * Generated by Bluespec Compiler (build 102a30c)
 * 
 * On Mon Feb  1 21:37:17 PST 2021
 * 
 */

/* Generation options: */
#ifndef __model_mkTop_bsim_h__
#define __model_mkTop_bsim_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTop_bsim.h"

/* Class declaration for a model of mkTop_bsim */
class MODEL_mkTop_bsim : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTop_bsim *mkTop_bsim_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTop_bsim();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTop_bsim();
}

#endif /* ifndef __model_mkTop_bsim_h__ */
